"""add description to category_rules

Revision ID: 3b55d5424768
Revises: 1aaa1e11fa00
Create Date: 2026-07-22 12:36:02.154070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b55d5424768'
down_revision: Union[str, None] = '1aaa1e11fa00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this succeeds against existing rows in every real
    # environment (dev/staging/prod), not just an empty table.
    op.add_column(
        'category_rules',
        sa.Column('description', sa.String(length=200), nullable=False, server_default=''),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_rules', 'description')
    # ### end Alembic commands ###
