"""add source file tracking to donors pledges donations

Revision ID: 5029ed073fdd
Revises: f23f192c8b48
Create Date: 2026-07-20 20:54:51.846738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5029ed073fdd'
down_revision: Union[str, None] = 'f23f192c8b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this succeeds against existing rows in every real
    # environment, not just an empty table - same reasoning as the
    # hide_donor_names migration just before this one.
    op.add_column('donations', sa.Column('source_file_name', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('donations', sa.Column('source_file_link', sa.Text(), nullable=False, server_default=''))
    op.add_column('donors', sa.Column('source_file_name', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('donors', sa.Column('source_file_link', sa.Text(), nullable=False, server_default=''))
    op.add_column('pledges', sa.Column('source_file_name', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('pledges', sa.Column('source_file_link', sa.Text(), nullable=False, server_default=''))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pledges', 'source_file_link')
    op.drop_column('pledges', 'source_file_name')
    op.drop_column('donors', 'source_file_link')
    op.drop_column('donors', 'source_file_name')
    op.drop_column('donations', 'source_file_link')
    op.drop_column('donations', 'source_file_name')
    # ### end Alembic commands ###
