"""initial schema

Revision ID: 8a8d8425fdc6
Revises:
Create Date: 2026-07-20 18:19:31.730435

Alembic's first real migration on this project - autogenerated against a
truly empty database, so it's the single source of truth for the schema
(replacing `Base.metadata.create_all`, which the app no longer calls).
Includes every table as of this commit, including Phase 2 pledge tracking
(donors/donations/pledges/pledge_campaigns/pledge_donor_matches), which
previously existed only via create_all with no migration of its own.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8d8425fdc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dedup_key', sa.String(length=60), nullable=False),
    sa.Column('donor_id', sa.String(length=40), nullable=True),
    sa.Column('fund', sa.String(length=120), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_dedup_key'), 'donations', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_fund'), 'donations', ['fund'], unique=False)
    op.create_table('donors',
    sa.Column('donor_id', sa.String(length=40), nullable=False),
    sa.Column('donor_number', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('joint_giver_id', sa.String(length=40), nullable=False),
    sa.Column('joint_giver_first_name', sa.String(length=120), nullable=False),
    sa.Column('joint_giver_last_name', sa.String(length=120), nullable=False),
    sa.Column('first_donated', sa.Date(), nullable=True),
    sa.Column('donation_count', sa.Integer(), nullable=False),
    sa.Column('total_given', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('donor_id')
    )
    op.create_index(op.f('ix_donors_email'), 'donors', ['email'], unique=False)
    op.create_table('pledge_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('fund_name', sa.String(length=120), nullable=False),
    sa.Column('goal_amount', sa.Float(), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recon_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bank_filename', sa.String(length=260), nullable=False),
    sa.Column('stripe_filename', sa.String(length=260), nullable=False),
    sa.Column('bank_line_count', sa.Integer(), nullable=False),
    sa.Column('stripe_line_count', sa.Integer(), nullable=False),
    sa.Column('matched_payout_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_stripe_bank_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('raw_bank_income_total', sa.Float(), nullable=False),
    sa.Column('raw_bank_expense_total', sa.Float(), nullable=False),
    sa.Column('bank_totals_by_day', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('no', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'no', name='uq_statement_category_no')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('pledges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_submitted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('monthly_amount', sa.Float(), nullable=False),
    sa.Column('contact_method', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['pledge_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'submission_id', name='uq_pledge_submission')
    )
    op.create_index(op.f('ix_pledges_campaign_id'), 'pledges', ['campaign_id'], unique=False)
    op.create_table('recon_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.String(length=20), nullable=False),
    sa.Column('date_posted', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('statement_description', sa.String(length=300), nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('bank_description', sa.Text(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.Column('is_stripe_payout', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recon_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_lines_run_id'), 'recon_lines', ['run_id'], unique=False)
    op.create_table('statement_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statement_category_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['statement_category_id'], ['statement_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statement_category_id', 'no', name='uq_statement_item_no')
    )
    op.create_table('chart_of_accounts',
    sa.Column('account_no', sa.String(length=20), nullable=False),
    sa.Column('statement_item_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('statement_detail', sa.String(length=120), nullable=False),
    sa.Column('statement_detail_no', sa.String(length=2), nullable=False),
    sa.Column('statement_description', sa.String(length=300), nullable=False),
    sa.Column('is_tax_deductible', sa.String(length=10), nullable=False),
    sa.Column('is_mandatory', sa.String(length=10), nullable=False),
    sa.Column('grouping', sa.String(length=120), nullable=False),
    sa.Column('is_youth_chaplain_share', sa.String(length=10), nullable=False),
    sa.Column('is_missions', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['statement_item_id'], ['statement_items.id'], ),
    sa.PrimaryKeyConstraint('account_no')
    )
    op.create_table('pledge_donor_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pledge_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.String(length=40), nullable=True),
    sa.Column('match_source', sa.String(length=10), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.donor_id'], ),
    sa.ForeignKeyConstraint(['pledge_id'], ['pledges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pledge_donor_matches_pledge_id'), 'pledge_donor_matches', ['pledge_id'], unique=True)
    op.create_table('accrual_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('is_reimbursement', sa.Boolean(), nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('check_invoice_name', sa.String(length=200), nullable=False),
    sa.Column('bank_description', sa.Text(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('split_parent_id', sa.Integer(), nullable=True),
    sa.Column('is_split', sa.Boolean(), nullable=False),
    sa.Column('receipt_file_id', sa.String(length=200), nullable=False),
    sa.Column('receipt_file_name', sa.String(length=300), nullable=False),
    sa.Column('receipt_web_view_link', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['chart_of_accounts.account_no'], ),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['split_parent_id'], ['accrual_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('account_no', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['chart_of_accounts.account_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['chart_of_accounts.account_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_rules_rule_type'), 'category_rules', ['rule_type'], unique=False)
    op.create_table('reconciliation_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('is_reimbursement', sa.Boolean(), nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('check_invoice_name', sa.String(length=200), nullable=False),
    sa.Column('bank_description', sa.Text(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.Column('dedup_key', sa.String(length=300), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('split_parent_id', sa.Integer(), nullable=True),
    sa.Column('is_split', sa.Boolean(), nullable=False),
    sa.Column('receipt_file_id', sa.String(length=200), nullable=False),
    sa.Column('receipt_file_name', sa.String(length=300), nullable=False),
    sa.Column('receipt_web_view_link', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['chart_of_accounts.account_no'], ),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['source_run_id'], ['recon_runs.id'], ),
    sa.ForeignKeyConstraint(['split_parent_id'], ['reconciliation_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_entries_dedup_key'), 'reconciliation_entries', ['dedup_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_entries_dedup_key'), table_name='reconciliation_entries')
    op.drop_table('reconciliation_entries')
    op.drop_index(op.f('ix_category_rules_rule_type'), table_name='category_rules')
    op.drop_table('category_rules')
    op.drop_table('budget_entries')
    op.drop_table('accrual_entries')
    op.drop_index(op.f('ix_pledge_donor_matches_pledge_id'), table_name='pledge_donor_matches')
    op.drop_table('pledge_donor_matches')
    op.drop_table('chart_of_accounts')
    op.drop_table('statement_items')
    op.drop_index(op.f('ix_recon_lines_run_id'), table_name='recon_lines')
    op.drop_table('recon_lines')
    op.drop_index(op.f('ix_pledges_campaign_id'), table_name='pledges')
    op.drop_table('pledges')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('statement_categories')
    op.drop_table('recon_runs')
    op.drop_table('pledge_campaigns')
    op.drop_index(op.f('ix_donors_email'), table_name='donors')
    op.drop_table('donors')
    op.drop_index(op.f('ix_donations_fund'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_dedup_key'), table_name='donations')
    op.drop_table('donations')
    op.drop_table('bank_accounts')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
