"""add hide_donor_names to users

Revision ID: f23f192c8b48
Revises: 8a8d8425fdc6
Create Date: 2026-07-20 19:01:06.661653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23f192c8b48'
down_revision: Union[str, None] = '8a8d8425fdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this succeeds against the existing `users` rows in
    # every real environment (dev/staging/prod), not just an empty table.
    op.add_column(
        'users',
        sa.Column('hide_donor_names', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hide_donor_names')
    # ### end Alembic commands ###
